// Code generated by "stringer -type statementType -linecomment"; DO NOT EDIT.

package gosql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DDL-0]
	_ = x[DQL-1]
	_ = x[DML-2]
	_ = x[DCL-3]
	_ = x[TCL-4]
}

const _statementType_name = "DDLDQLDMLDCLTCL"

var _statementType_index = [...]uint8{0, 3, 6, 9, 12, 15}

func (i statementType) String() string {
	if i >= statementType(len(_statementType_index)-1) {
		return "statementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statementType_name[_statementType_index[i]:_statementType_index[i+1]]
}
